######################## default configuration ####################
baseURL = "https://nishai.co.za"
title = "Nishai Kooverjee"
theme = "twenty-twenty-hugo"
languageName = "En"
languageCode = "en-us"
# post pagination
paginate = "2"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [] # desable language from here
# google analytics
googleAnalytics = "" # example : UA-123-45



############################## Output ###############################
[outputs]
home = ["HTML", "RSS", "JSON"]

# unsafe html
[markup.goldmark.renderer]
unsafe = true

[taxonomies]
category = "categories"
tag = "tags"
author = "author"

############################## navigation ###############################

# main menu
[[menu.main]]
name = "Home"
URL = "/"
weight = 1

[[menu.main]]
name = "Profile"
URL = "profile"
weight = 2

[[menu.main]]
name = "Blog"
URL = "blog"
weight = 3

[[menu.main]]
name = "Contact"
URL = "contact"
weight = 4

[[menu.main]]
name = "Sample Page"
URL = "sample-page"
weight = 5

# only desktop menu
[[menu.desktop]]
name = "My Profile"
URL = "profile"
weight = 1


#################### default parameters ################################
[params]
# Meta data
description = "This is meta description"
author = "Themefisher"

# favicon
[params.favicon]
favicon = "images/favicon.png"

# cookies
[params.cookies]
enable = false
expire_days = 2

# banner
[params.banner]
heading = "Hey! I'm Nishai.🤘🏽"
image = "images/cover.jpg"

# blog
[params.blog]
location = "🌍 Johannesburg, South Africa"
heading = "Welcome to my site.</br> I'm a Machine Learning Engineer, a Computer Science Masters graduate, a coffee enthusiast, and a fan of Kanye West and Apple devices."

# some music
[params.music]
enable = true
title = "In Rotation..."
sources = [
	"https://embed.music.apple.com/za/album/lp/1590920785",
	"https://embed.music.apple.com/za/album/23-seconds-bonus-track-version/265967783",
	"https://embed.music.apple.com/za/album/butterfly-3000/1569279719",
]

# gallery
[params.gallery]
enable = true

[[params.gallery.gallery_item ]]
image = "images/smilejozi.jpg"

[[params.gallery.gallery_item ]]
image = "images/mist.jpg"


# footer
[params.footer]
title = "About This Site"
content = "This may be a good place to introduce yourself and your site or include some credits."
address = "123 Main Street <br> New York, NY 10001"
hours = "Monday–Friday: 9:00AM–5:00PM <br> Saturday & Sunday: 11:00AM–3:00PM"
copyright = "Modified Hugo theme by [themefisher](https://themefisher.com/hugo-themes/)."

############################# social site ########################
[params.social]
# twitter = "#"
github = "https://github.com/nishai"
instagram = "https://instagram.com/adayinsamsara"
email = "nishai.kooverjee@gmail.com"
linkedin = "https://www.linkedin.com/in/nishai-kooverjee/"
